import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NextLink from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Portfolio Summary Site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1><NextLink href="/">みんなのポートフォリオ</NextLink></h1>
          <nav>
            <ul>
              <li><NextLink href="/webApp">Webアプリ</NextLink></li>
              <li><NextLink href="/webDesign">Webデザイン</NextLink></li>
              <li><NextLink href="/webSite">Webサイト</NextLink></li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>©︎2023 みんなのポートフォリオ</footer>
      </body>
    </html>
  )
}
