import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Portfolio Summary Site',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h1>みんなのポートフォリオ</h1>
          <nav>
            <ul>
              <li>Webアプリ</li>
              <li>Webデザイン</li>
              <li>Webサイト</li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>©︎2023 みんなのポートフォリオ</footer>
      </body>
    </html>
  )
}
